export const PENDING = 'PENDING'
export const FULFILLED = 'FULFILLED'
export const REJECTED = 'REJECTED'

export const GET_USERS = 'GET_USERS'
export const ADD_USER = 'ADD_USER'

export const TOGGLE_SIGNUP_OR_LOGIN = 'TOGGLE_SIGNUP_OR_LOGIN'

export const HANDLE_CHANGE_EMAIL = 'HANDLE_CHANGE_EMAIL'
export const HANDLE_CHANGE_USERNAME = 'HANDLE_CHANGE_USERNAME'
export const HANDLE_CHANGE_PASSWORD = 'HANDLE_CHANGE_PASSWORD'
export const TOGGLE_SIGNEDUP = 'TOGGLE_SIGNEDUP'
export const SET_USERNAMETAKEN_TRUE = 'SET_USERNAMETAKEN_TRUE'
export const SET_USERNAMETAKEN_FALSE = 'SET_USERNAMETAKEN_FALSE'

export const SET_INVALID = 'SET_INVALID'
export const SET_INVALID_SIGNUP = 'SET_INVALID_SIGNUP'

export const GET_CRYPTOS = 'GET_CRYPTOS'